openapi: 3.0.1
paths:
  /negotiations/request:
    post:
      operationId: initiateNegotiation
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractRequestMessage
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  example: null
                example: null
          description: default response
  /negotiations/{id}:
    get:
      operationId: getNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      responses:
        default:
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  example: null
                example: null
          description: default response
  /negotiations/{id}/agreement:
    post:
      operationId: createAgreement
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractAgreementMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
  /negotiations/{id}/agreement/verification:
    post:
      operationId: verifyAgreement
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractAgreementVerificationMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
  /negotiations/{id}/events:
    post:
      operationId: createEvent
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractNegotiationEventMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
  /negotiations/{id}/offers:
    post:
      operationId: providerOffer
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractOfferMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
  /negotiations/{id}/request:
    post:
      operationId: consumerOffer
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractRequestMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
  /negotiations/{id}/termination:
    post:
      operationId: terminateNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: null
      - in: header
        name: Authorization
        schema:
          type: string
          example: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JsonValue'
              example: null
              properties:
                empty:
                  type: boolean
                  example: null
                valueType:
                  type: string
                  enum:
                  - ARRAY
                  - OBJECT
                  - STRING
                  - NUMBER
                  - "TRUE"
                  - "FALSE"
                  - "NULL"
                  example: null
        description: https://w3id.org/dspace/v0.8/ContractNegotiationTerminationMessage
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
components:
  schemas:
    JsonObject:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/JsonValue'
      example: null
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
    JsonValue:
      type: object
      example: null
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
          example: null
