openapi: 3.0.1
paths:
  /identity-hub/query-commits:
    post:
      operationId: queryCommits
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /identity-hub/query-objects:
    post:
      operationId: queryObjects
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /identity-hub/collections:
    post:
      operationId: write
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /identity-hub/collections-commit:
    post:
      operationId: writeCommit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
