openapi: 3.0.1
paths:
  /transferprocess:
    get:
      operationId: getAllContractDefinitions
      parameters:
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - name: sortField
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferProcessDto'
    post:
      operationId: createContractDefinition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferProcessDto'
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /transferprocess/{id}:
    get:
      operationId: getContractDefinition
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferProcessDto'
    delete:
      operationId: deleteContractDefinition
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
components:
  schemas:
    DataRequestDto:
      type: object
      properties:
        assetId:
          type: string
        contractId:
          type: string
        connectorId:
          type: string
    TransferProcessDto:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        state:
          type: string
        errorDetail:
          type: string
        dataRequest:
          $ref: '#/components/schemas/DataRequestDto'
