name: Create EDC Release
on:
  workflow_dispatch:
    inputs:
      edc_version:
        description: 'Version string that is used for publishing. Appending -SNAPSHOT will create a snapshot release.'
        required: true
        type: string


env:
  EDC_VERSION: "v{{ github.event.inputs.edc_version || inputs.edc_version }}"

jobs:
  Prepare-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: releases

      # create tag using Github's own API
      - name: Create tag on current branch (main)
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.EDC_VERSION }}',
              sha: context.sha
            })

      # create merge commit
      - name: Merge main -> releases
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'releases'
          commit_message_template: 'Merge commit for version ${{ env.EDC_VERSION }}'
